#!/usr/bin/env bash
# Render an Alertmanager configuration that emails alerts, from .env values.
#
#   ALERT_EMAIL_TO          comma-separated recipients (required)
#   ALERT_EMAIL_FROM        sender address (required)
#   ALERT_SMTP_SMARTHOST    host:port of the SMTP submission server (required)
#   ALERT_SMTP_USERNAME     SMTP login; leave empty for an unauthenticated relay
#   ALERT_SMTP_REQUIRE_TLS  true (default) or false, only for a local test relay
#
# The SMTP password is never read from .env or printed. It is typed at a hidden
# prompt (or piped on stdin for automation) and stored mode 600 beside the
# rendered config in .data/alertmanager/config, which is mounted read-only into
# the Alertmanager container. Pass --reset-password to replace a stored one.
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"
# shellcheck source=scripts/lib/load-env.sh
source "$repo_root/scripts/lib/load-env.sh"
load_dotenv "$repo_root/.env"

reset_password=0
[[ "${1:-}" == "--reset-password" ]] && reset_password=1

fail() { echo "configure-alert-email: $*" >&2; exit 2; }

to="${ALERT_EMAIL_TO:-}"
from="${ALERT_EMAIL_FROM:-}"
smarthost="${ALERT_SMTP_SMARTHOST:-}"
username="${ALERT_SMTP_USERNAME:-}"
require_tls="${ALERT_SMTP_REQUIRE_TLS:-true}"
[[ -n "$to" && -n "$from" && -n "$smarthost" ]] ||
  fail "set ALERT_EMAIL_TO, ALERT_EMAIL_FROM and ALERT_SMTP_SMARTHOST in .env"

email_re='^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
IFS=',' read -r -a recipients <<<"$to"
for recipient in "${recipients[@]}"; do
  recipient="${recipient//[[:space:]]/}"
  [[ "$recipient" =~ $email_re ]] || fail "ALERT_EMAIL_TO contains an invalid address"
done
to="$(IFS=','; echo "${recipients[*]}" | tr -d '[:space:]')"
[[ "$from" =~ $email_re ]] || fail "ALERT_EMAIL_FROM is not an email address"
[[ "$smarthost" =~ ^[A-Za-z0-9.-]+:[0-9]{1,5}$ ]] || fail "ALERT_SMTP_SMARTHOST must be host:port"
[[ -z "$username" || "$username" =~ ^[A-Za-z0-9._%+@-]+$ ]] || fail "ALERT_SMTP_USERNAME has unsupported characters"
[[ "$require_tls" == true || "$require_tls" == false ]] || fail "ALERT_SMTP_REQUIRE_TLS must be true or false"

config_dir="$repo_root/.data/alertmanager/config"
umask 077
mkdir -p "$config_dir" "$repo_root/.data/alertmanager/data"
password_file="$config_dir/smtp-password"

if [[ -n "$username" ]] && { [[ $reset_password -eq 1 ]] || [[ ! -s "$password_file" ]]; }; then
  if [[ -t 0 ]]; then
    printf 'SMTP password for %s (input hidden): ' "$username" >&2
    IFS= read -r -s password
    printf '\n' >&2
  else
    IFS= read -r password || true
  fi
  [[ -n "$password" ]] || fail "empty SMTP password"
  printf '%s' "$password" >"$password_file.tmp"
  unset password
  chmod 600 "$password_file.tmp"
  mv "$password_file.tmp" "$password_file"
fi

auth_lines=""
if [[ -n "$username" ]]; then
  auth_lines="  smtp_auth_username: '${username}'
  smtp_auth_password_file: /etc/alertmanager/smtp-password"
fi

cat >"$config_dir/alertmanager.yml.tmp" <<EOF
# Generated by scripts/configure-alert-email.sh from .env. Do not edit by hand.
global:
  smtp_smarthost: '${smarthost}'
  smtp_from: '${from}'
  smtp_require_tls: ${require_tls}
${auth_lines}

route:
  receiver: family-email
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: family-email
    email_configs:
      - to: '${to}'
        send_resolved: true
        headers:
          Subject: '[Family Photo Cloud] {{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
EOF
chmod 600 "$config_dir/alertmanager.yml.tmp"
mv "$config_dir/alertmanager.yml.tmp" "$config_dir/alertmanager.yml"

# Validate with the same Alertmanager release Compose runs.
image="${ALERTMANAGER_IMAGE:-prom/alertmanager:v0.34.1}"
docker run --rm --entrypoint amtool --user "$(id -u):$(id -g)" \
  -v "$config_dir:/etc/alertmanager:ro" "$image" \
  check-config /etc/alertmanager/alertmanager.yml >/dev/null

# Point Compose at the rendered directory (idempotent).
if grep -q '^ALERTMANAGER_CONFIG_DIR=' .env; then
  sed -i.bak 's#^ALERTMANAGER_CONFIG_DIR=.*#ALERTMANAGER_CONFIG_DIR=./.data/alertmanager/config#' .env && rm -f .env.bak
else
  printf 'ALERTMANAGER_CONFIG_DIR=./.data/alertmanager/config\n' >>.env
fi
echo "Alertmanager email config written and validated (${#recipients[@]} recipient(s), smarthost ${smarthost})."
echo "Apply it with: make observability-up   then test with: make alert-test"
